spring:
  application:
    name: fraud-audit-engine
  
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  datasource:
    url: jdbc:postgresql://ep-silent-bonus-aorgjarr.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: ${NEON_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        options:
          model: gemini-2.5-flash

  data:
    redis:
      host: alert-quail-141238.upstash.io
      port: 6379
      password: ${UPSTASH_REDIS_PASSWORD}
      ssl:
        enabled: true

server:
  port: 8080

csv:
  aliases:
    account: cc_num,account,id,customer,nameorig
    amount: amt,amount,transaction_amount,value
    category: category,merchant_category,type
    location: city,location,state,ip,namedest

gemini:
  circuit-breaker:
    cooldown-ms: 120000
    max-retries: 2

aws:
  access-key-id: "d11168ef5ec192e69778c2437670b829"
  secret-access-key: "f67d14249d1d73d32197ed4484792d27f54db271f20b2f687fb7bb2527582168"
  region: "auto"
  s3:
    endpoint: "https://759dc11839520cb62fadf1d4b9863b29.r2.cloudflarestorage.com"
    bucket-name: "fraud-vault"